# Generated by Django 5.2.8 on 2025-11-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident', models.TextField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'new'), (1, 'processing'), (2, 'completed'), (3, 'fake'), (4, 'unknown')], db_index=True, default=0)),
                ('source', models.PositiveSmallIntegerField(choices=[(0, 'operator'), (1, 'monitoring'), (2, 'partner'), (3, 'unknown')], db_index=True, default=3)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
